---
- name: Update DNS record MX
  command: |
    yc dns zone replace-records --name {{ zimbra_dns_zone_name }} --record "@ 600 MX 0 mx.keqpup.ru"
  delegate_to: localhost
  become: false

- name: Update DNS record SPF
  command: |
    yc dns zone replace-records --name {{ zimbra_dns_zone_name }} --record '@ 600 TXT "v=spf1 a mx ip4:{{ external_ip_address }} ip4:{{ rout_public_ip }} -all"'
  delegate_to: localhost
  become: false

- name: ADD DNS record A home ip
  command: |
    yc dns zone add-records --name {{ zimbra_dns_zone_name }} --record "mx 600 A {{ rout_public_ip }}"
  delegate_to: localhost
  become: false