---
- name: Include local_dns_setup tasks
  include_tasks: local_dns_setup.yml
  tags: dns

- name: Include local_wg_keygen tasks
  include_tasks: local_wg_keygen.yml
  tags: keygen

- name: Include remote_pack_install tasks
  include_tasks: remote_pack_install.yml
  tags: pack

- name: Include local_docker_setup tasks
  include_tasks: local_docker_setup.yml
  tags: docker

- name: Include remote_vpn_setup tasks
  include_tasks: remote_vpn_setup.yml
  tags: vpn