---
- name: Install tcpdump epel-release wireguard-tools iptables
  dnf:
    name:
      - tcpdump
      - epel-release
      - wireguard-tools
      - iptables
    state: present

- name: Import GPG key
  command: rpm --import https://www.elrepo.org/RPM-GPG-KEY-elrepo.org
  ignore_errors: yes

- name: Install elrepo-release-8.el8.elrepo.noarch
  dnf:
    name:
      - https://www.elrepo.org/elrepo-release-8.el8.elrepo.noarch.rpm
    state: present
  ignore_errors: yes

- name: Install kmod-wireguard
  dnf:
    name:
      - kmod-wireguard
    state: present
  timeout: 300