version: "3.8"
services:
  wireguard:
    image: linuxserver/wireguard
    container_name: wg-server
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Moscow
    volumes:
      - ./config:/config
    ports:
      - "51820:51820/udp"
      - "25:25/tcp"
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.proxy_arp=1
    restart: unless-stopped