---
- hosts: zimbra
  become: yes
  become_method: sudo
  gather_facts: yes
  tasks:
    - include_role:
        name: vpn_setup
        tasks_from: local_dns_setup
    - include_role:
        name: vpn_setup
        tasks_from: local_wg_keygen
    - include_role:
        name: vpn_setup
        tasks_from: remote_pack_install
    - include_role:
        name: vpn_setup
        tasks_from: local_docker_setup
    - include_role:
        name: vpn_setup
        tasks_from: remote_vpn_setup